- src/api/db/build.ts
- src/api/db/job.ts
- src/app/components/app-build-details/app-build-details.component.html
- src/app/components/app-build-details/app-build-details.component.ts
- src/app/components/app-job/app-job.component.html
- src/app/components/app-job/app-job.component.ts
> feat(): calculated time of previous build

- src/api/process.ts
- src/files/Dockerfile
- src/files/scripts/abstruse-exec.sh
this PR will hopefully fix the issue about returning unappropriate exit code from executed command.
summary: I wrote a `bash` script for handling errors from command that is executed. now every command that is executed in the container goes through this script.
> [fix]: exit code issues

- src/api/image-builder.ts
- src/api/socket.ts
- src/app/components/app-images/app-images.component.html
- src/app/components/app-images/app-images.component.ts
- src/app/styles/buttons.sass
- src/app/styles/editor.sass
- src/app/styles/images.sass
https://github.com/bleenco/abstruse/issues/104
> feat(ui): image builder

- src/app/components/app-editor/app-editor.component.ts
- src/app/components/app-images/app-images.component.html
- src/app/components/app-images/app-images.component.ts
- src/app/components/app-logs/app-logs.component.html
- src/app/components/app-repository/app-repository.component.ts
- src/app/styles/buttons.sass
- src/app/styles/editor.sass
- src/app/styles/images.sass
- src/app/styles/logs.sass
UI updates with the approaching `1.0.0` release ...
> [ui]: updates

- src/api/docker.ts
- src/api/process.ts
- src/app/components/app-job/app-job.component.ts
- src/app/components/app-terminal/app-terminal.component.ts
> fix(image-message): adds error message to job output when image doesn't exists

- src/api/server-routes.ts
- src/api/system.ts
- src/app/components/app-setup/app-setup.component.html
- src/app/components/app-setup/app-setup.component.ts
- tests/unit/050_new-server-api-routes.spec.ts
> feat(status): check git installation

- e2e/060_builds.e2e.ts
- e2e/070_build.e2e.ts
- e2e/090_repository.e2e.ts
- src/api/docker.ts
- src/api/process-manager.ts
- src/api/process.ts
- src/api/socket.ts
- src/app/components/app-dashboard/app-dashboard.component.html
- src/app/components/app-dashboard/app-dashboard.component.ts
- src/app/components/app-job/app-job.component.html
- src/app/components/app-job/app-job.component.ts
- src/app/components/app-terminal/app-terminal.component.ts
- src/app/styles/build-details.sass
- src/app/styles/content.sass
- src/app/styles/dashboard.sass
- tests/unit/040_socket.spec.ts
> feat(debug): stop execution when enter debug mode

- Dockerfile
- hooks/build
- hooks/post_push
- package.json
This sets up a bunch of of the automation stuff needed for automatic dockerhub builds. 
Coupled with the configuration thats been made in the docker cloud service automatic builds based on tags will work.
> Automated builds

- package-lock.json
- package.json
- src/api/process-manager.ts
- src/api/server.ts
- src/api/socket.ts
- src/app/classes/rx-web-socket.class.ts
- src/app/services/config.service.ts
- tests/unit/040_socket.spec.ts
- webpack.api.js
we noticed many issues using `ws` with `RxJS` to get node memory out of heap (maybe because of bad implementation though). This PR introduce `uWebSockets` as a replacement for `ws`, written in C++. Not that we need better performance on websockets but let's see how things will come up with this as whole `socket.ts` file has been refactored.
> [refactor]: uwebsockets

- docs/ABSTRUSE_YML.md
I know this isn't perfect, but it's a beginning. I'm sure it'll help people who discover abstruse and I hope the maintainers will be tempted to find it a nice place to document some more complex behaviors I wasn't able to document due to my lack of understanding of JS/TS
Signed-off-by: Julien 'Lta' BALLET <contact@lta.io>
> Add basic syntax reference for abstruse.yml

- src/api/process-manager.ts
- src/api/process.ts
- src/app/components/app-job/app-job.component.ts
https://github.com/bleenco/abstruse/issues/304
> [deploy]: quick fix

- package-lock.json
- package.json
- src/api/image-builder.ts
- src/api/server-routes.ts
- src/app/components/app-header/app-header.component.html
- src/app/components/app-job/app-job.component.html
- src/app/styles/job.sass
- src/app/styles/nav.sass
> [feat]: raw logs

- Dockerfile
- src/api/commit-status.ts
fix(platform-server): change repository url
change status endpoint to use the configured repository.api_url
fix #350
> fix(platform-server): change repository url

- CHANGELOG.md
- package.json
- src/api/server-routes.ts
- src/app/components/app-images/app-images.component.spec.ts
- tests/unit/060_api-routes.spec.ts
> [security]: API access token

- src/app/components/app-terminal/app-terminal.component.ts
- src/styles/terminal.sass
> fix(fonts): fix terminal fonts on Linux (closes #362)

- src/api/webhooks.ts
- tests/e2e/utils/utils.ts
> fix(gogs): fix formatting JSON payload before calculating signature

- src/api/commit-status.ts
- src/api/config.ts
- src/api/db/access-token.ts
- src/api/db/build.ts
- src/api/db/migrations.ts
- src/api/db/repository.ts
- src/api/logger.ts
- src/api/process-manager.ts
- src/api/process.ts
- src/api/server-routes.ts
- src/api/utils.ts
- src/app/components/app-user/app-user.component.html
- src/app/components/app-user/app-user.component.spec.ts
- src/app/components/app-user/app-user.component.ts
closes https://github.com/bleenco/abstruse/issues/370 and https://github.com/bleenco/abstruse/issues/348
> feat(bitbucket): BitBucket OAuth integration

- CHANGELOG.md
- e2e/040_repositories.e2e.ts
- package.json
- src/api/commit-status.ts
- src/api/db/migrations.ts
- src/api/db/repository.ts
- src/api/server-routes.ts
- src/api/utils.ts
- src/app/components/app-repositories/app-repositories.component.html
- src/app/components/app-user/app-user.component.html
- src/app/components/app-user/app-user.component.ts
closes https://github.com/bleenco/abstruse/issues/374
> [fix]: GitLab integration fix

- Dockerfile
- package-lock.json
- src/api/config.ts
Clone only the `HEAD` of the required branch to save data and time. Addresses #431. Also includes some minor fixes. Let me know if you'd like them reversed.
> Work In Progress: Git clone --single-branch --depth 1

- README.md
Please give me thumbs up to merge @jkuri @KEMDAK
> docs(readme): add introduction and proofread

- configs/demo/default/docker-compose.yml
Updated --logger-level
closes #467
> Corrected --logger-level

- docs/INTEGRATING_GIT_PROVIDERS.md
> docs(provider): github integration

- web/abstruse/src/app/core/header/header.component.html
- web/abstruse/src/app/core/header/header.component.ts
- web/abstruse/src/styles/header.sass
This PR also adds state connecting in yellow color in case of retrying instead of showing just failed.
> feat(web): websocket indicator state connecting

- pb/api.proto
- server/api/api.go
- server/api/repo/create_env.go
- server/api/repo/delete_env.go
- server/api/repo/list_env.go
- server/api/repo/update_env.go
- server/cmd/wire.go
- server/core/env.go
- server/core/repo.go
- server/scheduler/scheduler.go
- server/store/envvariable/envvariable.go
- server/store/job/job.go
- server/store/store.go
- web/abstruse/src/app/repos/repos.module.ts
- web/abstruse/src/app/repos/settings-env-modal/settings-env-modal.component.html
- web/abstruse/src/app/repos/settings-env-modal/settings-env-modal.component.ts
- web/abstruse/src/app/repos/settings-envs/env-variable.model.ts
- web/abstruse/src/app/repos/settings-envs/settings-envs.component.html
- web/abstruse/src/app/repos/settings-envs/settings-envs.component.sass
- web/abstruse/src/app/repos/settings-envs/settings-envs.component.ts
- web/abstruse/src/app/repos/settings/settings.component.html
- web/abstruse/src/app/repos/settings/settings.component.ts
- web/abstruse/src/app/repos/shared/repos.service.ts
- worker/app/server.go
This PR will close https://github.com/bleenco/abstruse/issues/486
> feat: environment variables

- server/scheduler/scheduler.go
The most minimal fix that resolves the bug. Seems to be working in my test environment.
> Fixing issue with environment var splitting (issue #494)

- worker/docker/docker.go
- worker/docker/image.go
> fix(worker): fix pulling docker images from third party registries

- server/api/api.go
- server/api/build/log.go
- web/abstruse/angular.json
- web/abstruse/package-lock.json
- web/abstruse/package.json
- web/abstruse/src/app/builds/job/job.component.html
- web/abstruse/src/app/builds/job/job.component.sass
- web/abstruse/src/app/builds/job/job.component.ts
- web/abstruse/src/app/core/header/header.component.html
this implements and closes #521.
> feat(logs): view raw job log

- Makefile
- README.md
- web/abstruse/src/app/builds/job/job.component.ts
Looks like my previous pr's vanished - so here are they again
- build(Makefile): set CGO_ENABLED to 1
- docs(readme): fix link to the license 
and one little fix:
- fix(logs): use absolute path in logURL()
> Small fixes

- internal/auth/claims.go
- server/api/setup/user.go
- server/api/user/create.go
- server/api/user/login.go
- server/api/user/update.go
- server/api/user/update_profile.go
- server/core/user.go
- server/store/user/user.go
- web/abstruse/src/app/auth/login/login.component.html
- web/abstruse/src/app/profile/settings/settings.component.html
- web/abstruse/src/app/profile/settings/settings.component.ts
- web/abstruse/src/app/setup/shared/admin.model.ts
- web/abstruse/src/app/setup/user/user.component.html
- web/abstruse/src/app/setup/user/user.component.ts
- web/abstruse/src/app/teams/shared/user.model.ts
- web/abstruse/src/app/teams/user-list-item/user-list-item.component.html
- web/abstruse/src/app/teams/user-modal/user-modal.component.html
- web/abstruse/src/app/teams/user-modal/user-modal.component.ts
- web/abstruse/src/app/teams/users/users.component.html
- web/abstruse/src/app/teams/users/users.component.ts
fix(auth): Added check is user already exists when create new user
> feat(auth): Added support login by UserName

- pb/api.proto
- server/api/api.go
- server/api/repo/create_mount.go
- server/api/repo/delete_mount.go
- server/api/repo/list_mount.go
- server/api/repo/update_mount.go
- server/cmd/wire.go
- server/core/job.go
- server/core/mount.go
- server/core/repo.go
- server/parser/parser.go
- server/scheduler/scheduler.go
- server/store/build/build.go
- server/store/mounts/mounts.go
- server/store/repo/repo.go
- server/store/store.go
- web/abstruse/src/app/repos/repos.module.ts
- web/abstruse/src/app/repos/settings-mount-modal/settings-mount-modal.component.html
- web/abstruse/src/app/repos/settings-mount-modal/settings-mount-modal.component.ts
- web/abstruse/src/app/repos/settings-mount/mount-variable.model.ts
- web/abstruse/src/app/repos/settings-mount/settings-mount.component.html
- web/abstruse/src/app/repos/settings-mount/settings-mount.component.sass
- web/abstruse/src/app/repos/settings-mount/settings-mount.component.ts
- web/abstruse/src/app/repos/settings/settings.component.html
- web/abstruse/src/app/repos/shared/repos.service.ts
- worker/app/server.go
- worker/docker/docker.go
This pull request add an option to mount directories inside of the worker. Currently there are no specific options for mounting (such as mount read only), but it 'works'.
This partially solve #535
> feat(mount): Mount custom directories in docker

- pkg/gitscm/gitea.go
- pkg/gitscm/scm.go
- server/service/githook/parser.go
- web/abstruse/src/app/repos/settings/settings.component.html
- web/abstruse/src/app/repos/shared/repos.service.ts
Closes https://github.com/bleenco/abstruse/issues/544
> fix(webhooks): fix PR webhooks being triggered multiple times
